Repository genesiscommunitysuccess/blank-app-seed, pull requests merged in 2024-04, with the labels that each got.

#171 fix: create unique layout autosave key attribute GENC-266
  .genx/configure.js
  .genx/templates/route.template.hbs
Labels: bug

#180 feat: FDC3 support GENC-224
  .genx/configure.js
  .genx/prompts.js
  .genx/prompts/server.js
  .genx/prompts/ui.js
  .genx/templates/entityManager.hbs
  .genx/templates/grid.hbs
  .genx/templates/route.template.hbs
  .genx/utils.js
  client/package.json
  client/src/main/main.ts
  client/src/utils/fdc3.ts
  client/src/utils/index.ts
Labels: fdc3

#182 feat: new layout types GENC-286
  .genx/templates/gridLayout.hbs
  .genx/templates/horizontalLayout.hbs
  .genx/templates/route.template.hbs
  .genx/templates/tabsLayout.hbs
  .genx/utils.js
Labels: enhancement

#189 feat: add support for number formatting GENC-265
  .genx/templates/route.template.hbs
  .genx/utils.js
  client/package.json
  client/src/utils/formatters.ts
  client/src/utils/index.ts
Labels: enhancement
